### ISSUE TITLE
Scrolling to nonsensical locations

### ISSUE THREAD

**Issue by Sotiris-k** [justinthec/redditnav#35]
Hello,

After an update to the latest Chrome version 

![image](https://user-images.githubusercontent.com/4454324/30577001-38c0bae8-9d14-11e7-91f8-17624a9fa929.png)

The extension doesn't scroll to the parent comments anymore. Instead it just scrolls to locations which make no sense whatsoever.

**Comment by srdjanm88** [comment]
Hey, just took a look at this. Turns out the new update deprecated `document.body` in favour of `document.documentElement` which would result in us getting back the wrong distance to the next element requested.

**Comment by srdjanm88** [comment]
@Sotiris-k Hey, the fix should be live on the chrome store now. Try updating the extension if it hasn't already reached you, and let me know if the problem's been fixed

**Comment by Sotiris-k** [comment]
@srdjanm88 The issue is fixed. 

Thank you very much for your time and for this awesome extension!
