### ISSUE TITLE
Porting to Firefox

### ISSUE THREAD

**Issue by Sotiris-k** [justinthec/redditnav#40]
Are you guys cool if I have a go at porting this extension to firefox?

**Comment by srdjanm88** [comment]
Hey, I actually went ahead and wrote one a couple months back! We've just been kinda lazy (and apprehensive to a degree) with merging the change.

You can check it out [here](https://github.com/justinthec/redditnav/pull/39) - any feedback is welcome/appreciated!

**Comment by Sotiris-k** [comment]
That's great news! You saved me some time as well! I can't wait to see it in the firefox's extension directory.
